# Input paths
rewrite_path: "data/rewrites/2020/1_Original.tsv"
bert_reranker_path: "nboost/pt-bert-base-uncased-msmarco"
finetuned_checkpoint_path: null

# Output
output_name: "bm25_manual_body_k1_446_b_082" # Ranking output name

# Retrieval parameters
year: "2021"
query_rewrite: "manual"
retrieval: True
rewrite: False
reranker: null

# Elasticsearch
host_name: "localhost:9204"
es_index: "ms_marco_kilt_wapo_clean"
es_k1: 4.46
es_b: 0.82
es_field: "body"
