name: treccast
channels:
  - laura-dietz
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - black
  - flake8
  - pytest
  - pytest-cov
  - pytest-helpers-namespace
  - confuse
  - ftfy=5.8
  - nltk=3.6.2
  - pip:
    - trec-car-tools
