name: treccast
channels:
  - laura-dietz
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - black
  - flake8
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-helpers-namespace
  - confuse
  - ftfy=5.8
  - nltk=3.6.2
  - pytorch=1.8
  - transformers=4.9.0
  - elasticsearch=7.13.3
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - h5py
  - faiss-cpu
  - pip:
    - trec-car-tools
    - simpletransformers==0.61.13
    - pyserini
    - python-terrier
