name: treccast
channels:
  - laura-dietz
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - black
  - flake8
  - pre-commit
  - pytest
  - ftfy=5.8
  - pytorch=1.8
  - pytorch-lightning=1.4
  - transformers=4.9.0
  - nltk=3.6.2
  - elasticsearch=7.13.3
  - scikit-learn>=0.24.2
  - scipy==1.7.1
  - sklearn
  - confuse
  - pip:
    - trec-car-tools
