name: treccast
channels:
  - laura-dietz
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - black
  - flake8
  - pre-commit
  - pytest
  - nltk=3.6.2
  - elasticsearch=7.13.3
  - pip:
    - cbor==1.0.0
  