# Input paths
rewrite_path: "data/rewrites/2020/1_Original.tsv"
bert_reranker_path: "data/models/finetuned_models/simpletransformers_bert_nboost_pt-bert-base-uncased-msmarco_treccast/best_model/"
first_pass_file: "data/first_pass/2021/bm25_ensemble_manual.tsv"
# Output
output_name: "bm25_ensemble_manual_msmarco_treccast" # Ranking output name

# Retrieval parameters
year: "2021"
query_rewrite: "manual"
retrieval: True
rewrite: False
reranker: "bert"
base_bert_model: "bert-base-uncased"

# Elasticsearch
host_name: "localhost:9204"
es_index: "ms_marco_kilt_wapo_clean"
es_k1: 1.2
es_b: 0.75
es_field: "catch_all"
