# Input paths
rewrite_path: "data/rewrites/2020/1_Original.tsv"
bert_reranker_path: "nboost/pt-bert-base-uncased-msmarco"
finetuned_checkpoint_path: "data/models/fine_tuned_models/bert_TRECY1Y2.ckpt"
first_pass_file: "data/first_pass/2021/bm25_ensemble_manual.tsv"
# Output
output_name: "bm25_ensamble_manual_bert_finetuned_msmarco_y1y2" # Ranking output name

# Retrieval parameters
year: "2021"
utterance_type: "manual"
query_rewrite: "manual"
retrieval: True
rewrite: False
reranker: "bert_finetuned"

# Elasticsearch
host_name: "localhost:9204"
es_index: "ms_marco_kilt_wapo_clean"
es_k1: 1.2
es_b: 0.75
es_field: "catch_all"
