# Input paths
rewrite_path: "data/rewrites/2020/1_Original.tsv"
bert_reranker_path: "nboost/pt-bert-base-uncased-msmarco"
finetuned_checkpoint_path: "data/models/fine_tuned_models/lightning_logs/version_102/checkpoints/epoch=1-step=4859.ckpt"

# Output
output_name: "bm25_manual_bert_finetune_checkpoint" # Ranking output name

# Retrieval parameters
year: "2020"
utterance_type: "manual"
retrieval: True
rewrite: False
reranker: "bert_finetuned"

# Elasticsearch
host_name: "localhost:9204"
es_index: "ms_marco_kilt_wapo_clean"
es_k1: 1.2
es_b: 0.75
es_field: "catch_all"
