# Input/output paths
topics: "data/topics-2020/manual_evaluation_topics_annotated_v1.1.json" # Topics input path
rewrite_path: "data/rewrites/2020/1_Original.tsv"
output: "data/runs/2020/bm25_manual_bert_finetune_checkpoint.trec" # Ranking output path
bert_reranker_path: "nboost/pt-bert-base-uncased-msmarco"
finetuned_checkpoint_path: "data/models/fine_tuned_models/lightning_logs/version_102/checkpoints/epoch=1-step=4859.ckpt"
# Retrieval parameters
utterance: "manual"
preprocess: False
retrieval: True
rewrite: False
reranker: "bert_finetuned"
utterance_type: "raw"

# Elasticsearch
host_name: "localhost:9204"
es_index: "ms_marco_kilt_wapo_clean"
es_k1: 1.2
es_b: 0.75
es_field: "body"
