# Input paths
first_pass_file: null
rewrite_path: "data/rewrites/2020/1_Original.tsv"
bert_reranker_path: "nboost/pt-bert-base-uncased-msmarco"
finetuned_checkpoint_path: null

# Output
output_name: "bm25" # Ranking output name

# Retrieval parameters
year: "2021"
query_rewrite: null
retrieval: True
rewrite: False
reranker: null

# Elasticsearch
host_name: "gustav1.ux.uis.no:9204"
es_index: "ms_marco_kilt_wapo_clean"
es_k1: 1.2
es_b: 0.75
es_field: "catch_all"

k: 1000
