# Input/output paths
topics: "data/topics-2020/automatic_evaluation_topics_annotated_v1.1.json" # Topics input path
rewrite_path: "data/rewrites/2020/1_Original.tsv"
output: "data/runs-2020/bm25.trec" # Ranking output path
bert_reranker_path: "nboost/pt-bert-base-uncased-msmarco"

# Retrieval parameters
utterance: "raw"
preprocess: False
retrieval: True
rewrite: False
reranker: None
utterance_type: "raw"

# Elasticsearch
host_name: "localhost:9204"
es_index: "ms_marco_kilt_wapo_clean"
es_k1: 1.2
es_b: 0.75
es_field: "body"
