base_path: "/data/scratch/trec-cast-2021/data/first_pass/2021"
input_files:
  [
    "bm25.tsv",
    "bm25_manual.tsv",
    "bm25_automatic.tsv",
    "bm25_manual_k1_446_b_082.tsv",
    "bm25_manual_body.tsv",
    "bm25_manual_body_k1_446_b_082.tsv",
  ]
thresholds: [1000, 1000, 1000, 1000, 1000, 1000]
output_file: "ensemble_bm25.tsv"
