# Input paths
first_pass_file: null
rewrite_path: null
bert_reranker_path: null
finetuned_checkpoint_path: null

# Retrieval parameters
query_rewrite: null
rewrite: False
retrieval: True
reranker: null

# Number of documents to retrieve at each turn
k: 1000
num_prev_turns: 0

# Elasticsearch
host_name: "gustav1.ux.uis.no:9204"
es_k1: 1.2
es_b: 0.75
