# General config
year: 2021
k: 1000
num_prev_turns: 0

# Output path
output_name: raw_1k

# Rewrite defaults
query_rewrite: null
rewrite: False
rewrite_path: null

# Retrieval defaults
first_pass_file: null
es:
 host_name: "localhost:9204"
 k1: 1.2
 b: 0.75

prf:
  type: null
  num_documents: 10
  num_terms: 10

# Reranking with duoT5
duot5: False
duot5_topk: 50

# Re-ranking parameters
reranker: null

# ANCE dense retrieval
ance: no
ance_index:

# Rewriter for re-ranking
reranker_rewrite_path:

