# Input paths
first_pass_file: null
rewrite_path: null
bert_reranker_path: null
finetuned_checkpoint_path: null

# Output path
output_name: raw_1k

# Retrieval parameters
year: 2021
query_rewrite: null
rewrite: False
reranker: null

# Number of documents to retrieve at each turn
k: 1000
num_prev_turns: 0

# Elasticsearch
es:
 host_name: "gustav1.ux.uis.no:9204"
 k1: 1.2
 b: 0.75

