name: build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Cache conda dependencies
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if .github/environment.yaml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yaml') }}
    - name: Activate environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: treccast
        environment-file: environment.yaml
        use-only-tar-bz2: true
    - name: Install ANCE-PyTerrier
      run: |
        pip install --upgrade git+https://github.com/WerLaj/pyterrier_ance.git
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Run tests
      run: |
        pytest tests/local --cov=./ --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

